import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import './style.css'
const API=import.meta.env.VITE_API_URL||'http://localhost:8080'
const empty={name:'',hostname:'',ip_address:'',environment:'development',provider:'aws'}
function App(){const[servers,setServers]=useState([]),[form,setForm]=useState(empty),[error,setError]=useState(''),[loading,setLoading]=useState(true)
async function load(){setLoading(true);try{const r=await fetch(`${API}/api/v1/servers`);if(!r.ok)throw Error('Failed to load servers');setServers(await r.json());setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load()},[])
function change(e){setForm({...form,[e.target.name]:e.target.value})}
async function submit(e){e.preventDefault();try{const r=await fetch(`${API}/api/v1/servers`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw Error(b.error||'Failed to create server');setForm(empty);load()}catch(e){setError(e.message)}}
async function remove(id){if(!confirm('Delete this server?'))return;const r=await fetch(`${API}/api/v1/servers/${id}`,{method:'DELETE'});if(!r.ok)setError('Failed to delete server');else load()}
return <main><header><p className="eyebrow">CLOUD PLATFORM LAB · PHASE 1</p><h1>Infrastructure Inventory</h1><p className="intro">A small production-style workload for the DevOps and DevSecOps platform.</p></header><section className="panel"><h2>Add server</h2><form onSubmit={submit}><input name="name" placeholder="Name" value={form.name} onChange={change} required/><input name="hostname" placeholder="Hostname" value={form.hostname} onChange={change} required/><input name="ip_address" placeholder="IP address" value={form.ip_address} onChange={change} required/><select name="environment" value={form.environment} onChange={change}><option>development</option><option>staging</option><option>production</option></select><select name="provider" value={form.provider} onChange={change}><option>aws</option><option>gcp</option><option>on-premise</option></select><button>Create server</button></form></section>{error&&<p className="error">{error}</p>}<section className="panel"><div className="section-heading"><h2>Servers</h2><button className="secondary" onClick={load}>Refresh</button></div>{loading?<p>Loading...</p>:servers.length===0?<p className="muted">No infrastructure registered yet.</p>:<div className="table-wrap"><table><thead><tr><th>Name</th><th>Hostname</th><th>IP</th><th>Environment</th><th>Provider</th><th></th></tr></thead><tbody>{servers.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.hostname}</td><td>{s.ip_address}</td><td>{s.environment}</td><td>{s.provider}</td><td><button className="danger" onClick={()=>remove(s.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></main>}
createRoot(document.getElementById('root')).render(<App/>)
